.PHONY: build test check
build:
	go build -buildvcs=false -o tidesms ./cmd/tidesms

test:
	go test -race ./...

check:
	go build -buildvcs=false ./...
	go vet ./...
	go test -race ./...
	golangci-lint run
