CREATE TABLE contacts (id TEXT PRIMARY KEY, name TEXT NOT NULL, phone_number TEXT NOT NULL, theme TEXT NOT NULL DEFAULT '');
CREATE TABLE drafts (recipient TEXT PRIMARY KEY, body TEXT NOT NULL, revision INTEGER NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
PRAGMA user_version = 1;
